CREATE TABLE Users(
	username VARCHAR(30) PRIMARY KEY NOT NULL,
	name VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,
	email VARCHAR(100) NOT NULL,
	class VARCHAR(30) NOT NULL,
	password VARCHAR(255) NOT NULL
);
CREATE TABLE Questions(
	ID_Question INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	description MEDIUMTEXT ,
	matter VARCHAR(100) NOT NULL,
	sect VARCHAR(30) NOT NULL,
	username VARCHAR(30) NOT NULL,
	FOREIGN KEY(username) REFERENCES Users(username)
);
CREATE TABLE Answers(
	ID_Answer INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	description MEDIUMTEXT NOT NULL,
	correct BOOLEAN NOT NULL,
	ID_Question INTEGER NOT NULL,
	username VARCHAR(30) NOT NULL, 
	FOREIGN KEY(ID_Question) REFERENCES Questions(ID_Question),
	FOREIGN KEY(username) REFERENCES Users(username)
);
CREATE TABLE Files(
	ID_File INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	content MEDIUMBLOB NOT NULL,
	extension VARCHAR(10),
	ID_Question INTEGER NOT NULL,
	Id_Answer INTEGER NOT NULL,
	FOREIGN KEY(ID_Answer) REFERENCES Answers(ID_Answer),
	FOREIGN KEY(ID_Question) REFERENCES Questions(ID_Question)
);

  
